config/routes.rb
Rails.application.routes.draw do

  get 'team', to: 'team#show_team'
  get 'contact', to: 'contact#show_contact'
  get 'index', to: 'index#index'
	
  get 'show/:id', to: 'show#show', as: 'show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	has_many :linktags
	has_many :tags, through: :linktags

	belongs_to :user

	def self.find(id)

		gossip_array = Gossip.all
		return gossip_array[id.to_i]

	end

end

app/models/linktag.rb
class Linktag < ApplicationRecord

	belongs_to :tag
	belongs_to :gossip

end

app/models/tag.rb
class Tag < ApplicationRecord

	has_many :linktags
	has_many :gossips, through: :linktags

end

app/models/user.rb
class User < ApplicationRecord

	has_many :gossips

	belongs_to :city


	def self.find(id)
		puts '£' * 60
		puts id
		user_array = User.all
		return user_array[id.to_i]
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def show_contact
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/show_controller.rb
class ShowController < ApplicationController
  def show
		@gossip = Gossip.find(params[:id])
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def show_team
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/contact/show_contact.html.erb
<h1>CONTACT !</h1>
<p> Pour nous contacter il faut : </p>
<ul>
	<li> Brûler un arbre ancien </li>
	<li> Fabriquer un long tissu avec une peau de Yéti </li>
	<li> Faire des ronds de fumée à l'aide du tissu préalablement fabriqué </li>
</ul>

app/views/index/index.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
  </head>
  <body>

    <h1>Mon super site de gossip !</h1>

		<p>
		<% gossip_array = Gossip.all %>
		<% n=0 %>	
		<% gossip_array.each do |g| %>	
			<%= "Titre : " + g.title %>
			</br>
			<%= "Auteur : " +  g.user.first_name %> 
			</br>
			
			<%= link_to "Afficher",show_path(n)%>	
			<% n += 1 %>
			</br>
			</br>
		<% end %>	
		</p>
		
		<p>creer un potin</p>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipRailsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

		 <!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		



  </head>

  <body>

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

			
			
				
					
			<div class="container">
					
				 
					

				<nav class="navbar navbar-expand-md bg-dark navbar-dark">
				
					<div class = "navbar-header">
						<%= link_to "Accueil",index_path%>
					</div>

				
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
						<span class="navbar-toggler-icon"></span>
					</button>


					<div class="collapse navbar-collapse " id="collapsibleNavbar">
					
						<ul class="navbar-nav">
						
							<li class="nav-item active">
								<%= link_to "Contact",contact_path%>
							</li>
							
							<li class="nav-item">
								<%= link_to "Team",team_path%>
							</li>
							
							
							<li class="nav-item active">
								<%= link_to "Team",team_path%>
							</li>
							
						</ul>
						
					</div>
		
				</nav> 

			</div>
			
		
    <%= yield %>
	
  </body>
</html>

app/views/show/show.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
  </head>
	
  <body>
    <h1>Page Potin !</h1>

		<p>
			<%="Voici la page du potin" %> <br/>
				<br/>
			<%="Titre : " + @gossip.title%><br/>
				<br/>
			<%="Contenu : " + @gossip.content%><br/>
				<br/>
			<%="Auteur : " + @gossip.user.first_name + " " +@gossip.user.last_name%><br/>
				<br/>
			<%="Date de création : " + @gossip.created_at.to_s%><br/>

		</p>
	</body>
</html>
	

app/views/team/show_team.html.erb
<h1> TEAM </h1>
<p> Voici la team de ouf qui a fait ce site : 
	<ul>
		<li> Pikachu </li>
		<li> Carapuce </li>
		<li> Salamèche </li>
		<li> Bulbizarre </li>
	</ul>
</p>